services :
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./rproxy/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
